### PR TITLE
Fixing issues with Obis Sync

### PR DESCRIPTION
**Pull request by tzielins**
Firstly syn job now runs as the user who registered an asset so that depending assays/datafiles can be created.
Secondly improved error handling so that the messages are more meangful and better propagate.

### CODE REVIEW

**Comment by stuzart** [comment]
this PR reverts the fix to the error messages, which will now once again reveal username and passwords

**Comment by tzielins** [comment]
I didn't get any merge warnings and I pulled the branch on friday.

I will not be able to touch seek before Wednesday.

Let me know where are your fixes and I will add them.

T.




-------- Original message --------

**Comment by stuzart** [comment]
I'll merge the PR and look again at the error message. The problem was https://github.com/seek4science/seek/pull/74/commits/876de14e26b19928b9bf17dccd8493652f849824#diff-16c8fb3842542a59744b9f9026d85145R138 - the full exception message contains the java command that contains credentials.

**Comment by tzielins** [comment]
I would say the java error message should be fixed instead. I can have a look at the client but on wednesday.

T.


-------- Original message --------

**Pull request merged**
