### PR TITLE
Ldap truncate username

### PR DESCRIPTION
**Pull request by abecam**
A very small change to truncate usernames coming from OAuth so they don't go above the size limit(40) and don't clash (so allow the method to avoid clashes to work).

### CODE REVIEW

**Comment by stuzart** [comment]
would removing or increasing the limit on the User.login also solve the problem?

**Comment by stuzart** [comment]
> > would removing or increasing the limit on the User.login also solve the problem?
> 
> Yes, the issue we have is that our identity server provide a kind of long hash for the uid, so >40 chars (I believe around 70). The truncation has the benefit of not worrying about the maximum size anymore. Feel free to reject the PR :) !

So, if we increased the limit to 120 (to avoid very long usernames), that would make this PR redundant, or is there still potential for name clashes ?

**Comment by abecam** [comment]
> > > would removing or increasing the limit on the User.login also solve the problem?
> > 
> > 
> > Yes, the issue we have is that our identity server provide a kind of long hash for the uid, so >40 chars (I believe around 70). The truncation has the benefit of not worrying about the maximum size anymore. Feel free to reject the PR :) !
> 
> So, if we increased the limit to 120 (to avoid very long usernames), that would make this PR redundant, or is there still potential for name clashes ?

The unique_name method should avoid any name clashes anyway. Otherwise it would be difficult to be 100% sure as it depends on the OAuth provider.

**Comment by stuzart** [comment]
> > > > would removing or increasing the limit on the User.login also solve the problem?
> > > 
> > > 
> > > Yes, the issue we have is that our identity server provide a kind of long hash for the uid, so >40 chars (I believe around 70). The truncation has the benefit of not worrying about the maximum size anymore. Feel free to reject the PR :) !
> > 
> > 
> > So, if we increased the limit to 120 (to avoid very long usernames), that would make this PR redundant, or is there still potential for name clashes ?
> 
> The unique_name method should avoid any name clashes anyway. Otherwise it would be difficult to be 100% sure as it depends on the OAuth provider.

I've created a PR #1369 - which if you approve and believes things, then you can close the PR

**Pull request closed without merging**
