### PR TITLE
Sample and Multi Sample form element

### LINKED ISSUE #1557: Difference between "Registered sample" attribute type and its variation "multiple"
Attribute types "Registered sample" and its "multiple" variation behave differently.

Use case: User selects the sample "Vanilla test Sample 3" as value for a registered sample attribute for a sample. If the referenced sample "Vanilla test Sample 3" gets Hidden or Deleted, the referenced sample is
- in "Registered sample": not visible nor selectable from the dropdown menu for the User
- in "Registered sample multiple": STILL visible AND selectable from the dropdown menu for the User. This seems a bug; this should behave as "Registered sample".

Screenshot 2023-08-09 at 11 43 38

### PR DESCRIPTION
**Pull request by stuzart**
Use select2 for both Single and Multiple Sample entry (requires handling params as an array for both cases, whereas the api still takes a non array for single case)

Also make sure non visible samples are filtered from the available options.

Also checked that non visible samples are shown as hidden when displaying the parent sample

- Fixes #1557

### CODE REVIEW

**Review by fbacall — COMMENTED** [review]
What happens if a user creates a sample, and links a private sample that only they can view, then another user (with edit permissions) edits the original sample - can they see the private sample? 

and if not, does it unlink the private sample when they submit the form?

**Comment by floradanna** [comment]
To the best of my knowledge, the hidden linked sample remains labelled as "hidden" but the other user can still edit the sample if he/she has editing rights over the sample.

**Comment by stuzart** [comment]
> What happens if a user creates a sample, and links a private sample that only they can view, then another user (with edit permissions) edits the original sample - can they see the private sample?
> 
> and if not, does it unlink the private sample when they submit the form?

I tried testing it, and the private sample is inculded and it's title revealed. It isn't stripped out when resubmitting. I'm changing it so that the title is kept hidden.

**Comment by floradanna** [comment]
Indeed, **in the form** the title is revealed for registered samples (multiple), but not for registered sample (single). See #1557 
When looking at the sample instead, the label "hidden" is shown.

**Review by fbacall — APPROVED** [review]

**Pull request merged**
